### PR TITLE
Added compile.snow.ps1 to list of ignored files in cleanup

### PR DESCRIPTION
**Pull request by cyberzed**
Just a simple addition of ignoring a single powershell script just like the bat, sorta tempted to spike a .snowignore file with the basics in it.

### CODE REVIEW

**Comment by sgrassie** [comment]
See my pull request #130, which will allow a much more dynamic way of configuring ignorable files /cc @phillip-haydon

**Comment by phillip-haydon** [comment]
@sgrassie yeah when I read it last night I remembered your PR. Blah I'm making time Saturday morning to sort out all the PRs and fix a couple of bugs. 

Sorry for being so slack :( just so busy.

**Comment by sgrassie** [comment]
We're all busy. I for one only have a small number of spiked unit tests for that stuff I was talking about in #126 months ago. Always so busy with :family: 

If I can get chance, I'll fix up that PR to fix the merge errors github is reporting.

**Comment by phillip-haydon** [comment]
@sgrassie @cyberzed OK so I pulled everything on Saturday and it doesn't build locally. Haha so I was fixing up some stuff and tidying some code.

Sunday I was too hung over to look at my computer so I'll try finish this tomorrow night. 

Decent clean up coming and keeping the default list in code and overriding with @sgrassie's PR.

**Comment by cyberzed** [comment]
@phillip-haydon I assume you mean #130 and not this one :smile:

**Comment by phillip-haydon** [comment]
Pulling this now (finally, so sorry :() since @sgrassie needs to fix up his PR ;)

**Pull request merged**
